/** Hosting + official signing catalog (Platforms view). */

import type { ProviderWizard } from "./types";

export const PLATFORM_WIZARDS: ProviderWizard[] = [
  {
    id: "orbit",
    group: "Hosting",
    title: "Orbit",
    blurb: "Local Orbit deploy when the project is Orbit-configured.",
    openUrl: "https://github.com/Dendro-X0/orbit",
    needsPublic: true,
    deployArgs: "status",
    steps: [
      "Set intent to Public (Local skips hosted deploy).",
      "Confirm Orbit is on PATH and this repo has orbit.toml / .orbit.",
      "Run deploy status / ship from Ritual or Tools — Studio does not upload for you.",
      "Copy the live URL, then Confirm Live check on Publish (or paste into last-run evidence).",
    ],
  },
  {
    id: "cloudflare",
    group: "Hosting",
    title: "Cloudflare",
    blurb: "Workers / Pages via wrangler — Studio opens the dashboard.",
    provider: "cloudflare",
    openUrl: "https://dash.cloudflare.com",
    needsPublic: true,
    deployArgs: "deploy --provider cloudflare",
    steps: [
      "Open Cloudflare and select the Workers or Pages project.",
      "Use Portal steps → Login CLI (opens a terminal for wrangler/Orbit OAuth).",
      "Deploy with wrangler or Orbit on your machine; put host secrets via Env (never into Studio).",
      "Copy the *.workers.dev / custom URL → Publish Live check → Confirm.",
    ],
  },
  {
    id: "vercel",
    group: "Hosting",
    title: "Vercel",
    blurb: "Vercel project link and deploy CLI.",
    provider: "vercel",
    openUrl: "https://vercel.com/dashboard",
    needsPublic: true,
    deployArgs: "deploy --provider vercel",
    steps: [
      "Open Vercel and select or import the project.",
      "Portal steps → `vercel login` / whoami when Publish asks for OAuth.",
      "Deploy from the Vercel CLI or dashboard; set env vars on Vercel (not in Studio).",
      "Copy the production URL → Publish Live check → Confirm.",
    ],
  },
  {
    id: "netlify",
    group: "Hosting",
    title: "Netlify",
    blurb: "Netlify site deploy.",
    provider: "netlify",
    openUrl: "https://app.netlify.com",
    needsPublic: true,
    deployArgs: "deploy --provider netlify",
    steps: [
      "Open Netlify and select or create the site.",
      "Portal steps → Netlify login when the plan asks for it.",
      "Deploy with Netlify CLI or UI; put site env on Netlify.",
      "Copy the site URL → Publish Live check → Confirm.",
    ],
  },
  {
    id: "github-pages",
    group: "Hosting",
    title: "GitHub Pages",
    blurb: "Static docs / marketing — Settings → Pages (not PAT portal).",
    openUrl: "https://github.com",
    openLabel: "Open GitHub",
    docsUrl:
      "https://docs.github.com/en/pages/getting-started-with-github-pages/creating-a-github-pages-site",
    needsPublic: true,
    steps: [
      "Open your repo on GitHub → Settings → Pages (branch or Actions publishing source).",
      "Publish the site yourself — Studio does not push Pages.",
      "Use Docs for the official tutorial. Need `gh` login / PAT for CI? Use the Portal view with GitHub — not this card.",
      "Copy the Pages URL → Publish Live check / marketing.deploy → Confirm.",
    ],
  },
  {
    id: "fly",
    group: "Hosting",
    title: "Fly.io",
    blurb: "flyctl auth + secrets — Studio opens the dashboard and portal steps.",
    provider: "fly",
    openUrl: "https://fly.io/dashboard",
    needsPublic: true,
    steps: [
      "Portal steps → Login CLI (`fly auth login`).",
      "Deploy with flyctl on your machine — Studio does not upload.",
      "Secrets: `fly secrets set` (Docs on the env portal step).",
      "Copy the app URL → Publish Live check → Confirm.",
    ],
  },
  {
    id: "railway",
    group: "Hosting",
    title: "Railway",
    blurb: "railway login + Variables — Studio opens tokens / dashboard.",
    provider: "railway",
    openUrl: "https://railway.app/dashboard",
    needsPublic: true,
    steps: [
      "Portal steps → Login CLI (`railway login`).",
      "Account tokens at railway.com/account/tokens when CI needs them (not both TOKEN env vars).",
      "Put service variables on Railway — never in Studio.",
      "Copy the public URL → Publish Live check → Confirm.",
    ],
  },
  {
    id: "apple-sign",
    group: "Official signing",
    title: "Apple",
    blurb: "Developer certificates, notarization, App Store Connect.",
    openUrl: "https://developer.apple.com/account",
    needsPublic: false,
    steps: [
      "Open Apple Developer — certificates / profiles stay on their UI.",
      "Run Signet graduate / notarize locally when your layout needs it (Sign panel).",
      "App Store Connect submit is on Apple — then Confirm on Publish.",
    ],
  },
  {
    id: "microsoft-sign",
    group: "Official signing",
    title: "Microsoft",
    blurb: "Authenticode / MSIX / Partner Center.",
    openUrl: "https://partner.microsoft.com/dashboard",
    needsPublic: false,
    steps: [
      "Open Partner Center (or your cert portal) and finish signing there.",
      "Self-sign with Signet is enough for many local Windows cuts.",
      "Store submit stays on Microsoft — Confirm on Publish after.",
    ],
  },
  {
    id: "google-play",
    group: "Official signing",
    title: "Google Play",
    blurb: "Play Console listing and upload (when mobile is in scope).",
    openUrl: "https://play.google.com/console",
    needsPublic: false,
    steps: [
      "Open Play Console when mobile is in Scopes.",
      "Upload / review on Google — Studio does not hold Play credentials.",
      "Confirm the listing / submit step on Publish when it is current.",
    ],
  },
];

export const PLATFORM_GROUPS = ["Hosting", "Official signing"] as const;
